name: Push Build to JFrog Artifactory

on:
  push:
    branches:
      - main  # Trigger this action on a push to the 'main' branch

jobs:
  push-artifact:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Upload build artifact to JFrog Artifactory
      - name: Push build artifact to JFrog Artifactory
        run: |
          curl -k -u ${{ secrets.ARTIFACTORY_API_KEY }}: \
          -X PUT \
          -T yes.py \
          "${{ secrets.ARTIFACTORY_URL }}/artifactory/${{ secrets.ARTIFACTORY_REPO }}/yes.py"
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}  
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
          ARTIFACTORY_REPO: ${{ secrets.ARTIFACTORY_REPO }}
