name: Set up JFrog CLI and deploy to Artifactory

on:
  push:
    branches:
      - main  # Trigger this on push to main branch

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the job

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://isiih.shop  # URL of your JFrog Artifactory instance
      with:
        oidc-provider-name: vinoddevtools  # Name of your OIDC provider to authenticate

    - name: Test JFrog CLI Installation
      run: jfrog --version  # Verify that JFrog CLI is installed correctly

    - name: Deploy to JFrog Artifactory
      run: |
        jfrog rt u yes.py https://github.com/Vinod-DevTools/github-- --flat=true
      env:
        JF_URL: https://isiih.shop  # JFrog Artifactory URL
